### ISSUE TITLE
Master todo

### ISSUE THREAD

**Issue by chondromalasia** [chondromalasia/weatheranalytics#8]
* [ ] - deploy image to vps and run - 
* [ ] - add api calls to it
* [ ] - tests
* [ ] - add database - efs
